version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: main
      MYSQL_USER: dev
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev-network

  pintmate:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production


networks:
  dev-network:
    driver: bridge

volumes:
  db-data:
    driver: local
